-- Schéma de la passerelle. Ce fichier fait foi : les entités JPA sont
-- validées contre lui au démarrage (ddl-auto: validate), jamais
-- l'inverse. H2 en mémoire, recréé à chaque lancement.

-- Les clients fictifs de la démonstration. La formule est le contexte
-- injecté dans la recherche documentaire du service IA.
CREATE TABLE clients (
    id       VARCHAR(20)  PRIMARY KEY,
    nom      VARCHAR(60)  NOT NULL,
    formule  VARCHAR(10)  NOT NULL,
    CONSTRAINT formule_connue
        CHECK (formule IN ('essentiel', 'confort', 'premium'))
);

-- Une session = une conversation. L'état du dialogue en cours (le JSON
-- que FastAPI rend et attend) est conservé ici entre deux messages :
-- c'est LE noyau de l'étape 11, le front ne le voit plus jamais.
-- client_id nul = mode visiteur, sans contexte de formule.
CREATE TABLE sessions (
    id          VARCHAR(36)  PRIMARY KEY,
    client_id   VARCHAR(20),
    etat_json   CLOB,
    creee_le    TIMESTAMP    NOT NULL,
    active_le   TIMESTAMP    NOT NULL,
    CONSTRAINT session_client
        FOREIGN KEY (client_id) REFERENCES clients (id)
);

-- Journal des échanges, une ligne par message traité : l'exigence de
-- journalisation du cadrage (intention, confiance, chemin, latences).
-- Requêtable dans la console H2 pendant la démonstration.
CREATE TABLE echanges (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    VARCHAR(36)  NOT NULL,
    recu_le       TIMESTAMP    NOT NULL,
    message       VARCHAR(1000) NOT NULL,
    chemin        VARCHAR(20),
    intention     VARCHAR(40),
    confiance     DOUBLE,
    formule       VARCHAR(10),
    latence_classification_ms  INT,
    latence_recherche_ms       INT,
    latence_generation_ms      INT,
    latence_totale_ms          INT,
    CONSTRAINT echange_session
        FOREIGN KEY (session_id) REFERENCES sessions (id)
);

CREATE INDEX idx_echanges_session ON echanges (session_id, recu_le);